Repository AkshayNachappa/Hacktoberfest_2022, pull requests merged in 2021-10, with the labels that each got.

#3 Create parallel_processing.py
  PYTHON/parallel_processing.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#2 Create linersearch.java
  JAVA/linersearch.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#4 Finding number of 2x2 squares can fit inside a right angled isosceles triangle
  JAVA/2x2_Squares_in_a_triangle.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#7 QuickSort,MergeSort
  JAVA/MergeSort.java
  JAVA/QuickSort.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#8 Implementation of Bubble Sort Using Two Stacks
  JAVA/Bubble_Sort_Using_Two_Stacks.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#10 Added search and graph cpp
  CPP/bfs.cpp
  CPP/binarySearch.cpp
  CPP/dfs.cpp
  CPP/linearSearch.cpp
  CPP/treeCreate.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#11 Create BubbleSort
  CPP/BubbleSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#13 SPLIT THE ARRAY AND ADD THE FIRST PART TO THE END
  JAVA/SplitAndAdd.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#26 Details added
  CONTRIBUTING.md
  CPP/Stack.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#21 Create Pascal_triangle.cpp
  CPP/Pascal_triangle.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#36 Create Multiplication_table.c
  C/Multiplication_table.c
Labels: hacktoberfest-accepted

#37 Update Stack.cpp
  CPP/Stack.cpp
Labels: enhancement, hacktoberfest-accepted

#39 Create Factorial.c
  C/Factorial.c
Labels: hacktoberfest-accepted

#41 Update StringEncryption.c
  C/StringEncryption.c
Labels: hacktoberfest-accepted

#43 Added bit mask
  PYTHON/bitmask.py
Labels: hacktoberfest-accepted

#42 add password generator
  PYTHON/advanced_password_generator.py
Labels: hacktoberfest-accepted

#44 Added subset generation
  PYTHON/subset_generation.py
Labels: hacktoberfest-accepted

#45 HashSet Added
  JAVA/HashSet.Java
Labels: hacktoberfest-accepted

#46 Pairs of integers from m to n
  PHP/GeneratePairs.php
Labels: hacktoberfest-accepted

#49 Rock-Paper-Scissor-Game
  PYTHON/RockPaperScissor/README.md
  PYTHON/RockPaperScissor/Rock-Paper-Scissor.py
Labels: hacktoberfest-accepted

#50 find position of number in matrix
  C/Student_grade.c
  CONTRIBUTING.md
  numposinmatrix.c
Labels: hacktoberfest-accepted

#51 Added Primitive_numbers to C Folder
  C/Primitive_numbers.c
Labels: hacktoberfest-accepted

#52 Traversing a binary search tree
  C/binary_search_tree.c
Labels: hacktoberfest-accepted

#53 Create postfix_evaluation.c
  C/postfix_evaluation.c
Labels: hacktoberfest-accepted

#54 Program to print half pyramid using alphabets in c language
  C/pyramid_of_alphabets.c
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#56 Display string length using character pointers
  C/string_char_pointer.c
Labels: hacktoberfest-accepted

#58 add algorithm
  PYTHON/dijkshtra.py
Labels: hacktoberfest-accepted

#60 Wave array in JAVA
  CONTRIBUTING.md
  JAVA/wave_array.java
Labels: hacktoberfest-accepted

#256 Create HackerrankModAutomation.js
  JS/HackerrankModAutomation.js
Labels: hacktoberfest-accepted

#257 added a comment line
  PYTHON/HCF.py
Labels: hacktoberfest-accepted

#258 Added 5 new solutions
  CPP/Calculate Money In Leetcode Bank.cpp
  CPP/Closest Subsequence Sum.cpp
  CPP/Game Of Life.cpp
  CPP/Length Of Last Word.cpp
  CPP/Longest  Increasing  Subsequence.cpp
Labels: hacktoberfest-accepted

#262 Added Algorithm checkGoodPairsInArray.js
  JS/checkGoodPairsInArray.js
Labels: hacktoberfest-accepted

#264 python code to check for prime number
  PYTHON/prime numbers indicator.py
Labels: hacktoberfest-accepted
